### ISSUE TITLE
How

### ISSUE THREAD

**Issue by majovec** [BukkitPE/BukkitPE#1]
How to instal ??
This is only Bukkit or PM server (change)

**Comment by xZeroMCPE** [comment]
This is BukkitPE it's a server software to make MCPE server. It has more features then pocketmine :)

**Comment by majovec** [comment]
i have MCPE server and how make how to phar BukkitPE

**Comment by xZeroMCPE** [comment]
Go here: https://github.com/BukkitPE/BukkitPE
then look for the download link, after clicking BukkitPE should download then extract the zip file and run the start.cmd for windows and start.sh for linux. :)

**Comment by majovec** [comment]
ouuu i have server on website hosting :( (only control panel on website,  )

**Comment by xZeroMCPE** [comment]
Message you're host, and provide them this link: https://github.com/BukkitPE/BukkitPE
and they will add it. :)

**Comment by majovec** [comment]
unfortunately they give only the official PocketMine

**Comment by xZeroMCPE** [comment]
Just contact them and link them to BukkitPE and tell them, i'm sure they will use it. Give them a reason ;)
