### ISSUE TITLE
Beacon Functionality

### ISSUE THREAD

**Issue by MunkySkunk** [BukkitPE/BukkitPE#14]
This is not a bug more a request. Are there any plans to bring Beacons into BukkitPE Creative?

**Comment by xZeroMCPE** [comment]
Yes, i was thinking of adding that, Anyway if you have any of these questions you are welcome to post it at our forum which is forums.bukkitpe.net

**Comment by MunkySkunk** [comment]
Perfect thank you, will use the forum :)

**Comment by xZeroMCPE** [comment]
No, problem man. :)

**Comment by DelxHQ** [comment]
beacons aren't in MCPE yet. we cannot add them until there in the game.
