### ISSUE TITLE
This is ClearSky but edited.

### ISSUE THREAD

**Issue by DaPigGuy** [BukkitPE/BukkitPE#17]
All the code is edited code from ClearSky. @thebigsmileXD

**Comment by xZeroMCPE** [comment]
Is there something wrong? It uses a GPL lincense. Pleas next time read before posting thanks,

**Comment by DaPigGuy** [comment]
Wow. You're claiming someone's code and not giving a single piece of credit.

**Comment by xZeroMCPE** [comment]
Credits will be giving ;) thanks for reminding me anyway thanks again.

**Comment by xZeroMCPE** [comment]
EDIT: Credit has been added. Thanks

**Comment by inxomnyaa** [comment]
Why don't you just join ClearSky?

**Comment by xZeroMCPE** [comment]
What do you mean by "Joinninig?? "

**Comment by inxomnyaa** [comment]
*Joining

I mean join our ClearSky team. We have 2 developers and @MCPEPIG who pushes often.

**Comment by xZeroMCPE** [comment]
Sure, but BukkitPE will still be going on
