### ISSUE TITLE
is that for 0.14.0 alpha build 3?

### ISSUE THREAD

**Issue by Erkam246** [BukkitPE/BukkitPE#2]
or can you update that to 0.14.0 build 3

**Comment by DelxHQ** [comment]
We will look into doing this.

**Comment by Erkam246** [comment]
OK

**Comment by xZeroMCPE** [comment]
We've added the beta version that works with MCPE 14.4 (Build 4) Please check https://github.com/BukkitPE/BukkitPE    read the readme.md and you"ll see somewhere that should talk about the beta release...
