### ISSUE TITLE
[Deleted]

### ISSUE THREAD

**Issue by PocketKiller** [BukkitPE/BukkitPE#21]
I can't call this useless repo BukkitPE, you forked ClearSky while you need to fork PocketMine, so I can call this clearsky, everything is done on clearsky, you made nothing, that's why not many users use this, also you got banned from PocketMine Forums for advertising @AndreTheGamer

**Comment by AndreTheGamer** [comment]
Hi, can you stop spamming BukkitPE repo? get a life man

**Comment by PocketKiller** [comment]
Hmm sorry. I just created this issue 1 time, Also I wasn't making a war :smile:

**Comment by AndreTheGamer** [comment]
ok
