### ISSUE TITLE
0.14.0

### ISSUE THREAD

**Issue by MunkySkunk** [BukkitPE/BukkitPE#24]
I applied the new phar file for 0.14 this morning and when trying to connect to it with the latest 0.14 app on the ipad it says that it is not the correct version and shows as 0.14.0.4 written in red with a green dot but will not load.

**Comment by xZeroMCPE** [comment]
What MCPE version do you have exactly?

EDIT: I just looked in the app store and the lastest version was 0.14 , So i will be updating BukkitPE to that version.

**Comment by MunkySkunk** [comment]
It 0.14.0. Just updated on App Store today.

**Comment by xZeroMCPE** [comment]
Alright, i will be updating BukkitPE to support 0.14.0

**Comment by xZeroMCPE** [comment]
It has been added, Please check jenkins.BukkitPE.net and download the stable build for 14.0 , If you have any issues please tell us via: Forums.BukkitPE.net
