### ISSUE TITLE
BukkitPE Recuiting dev

### ISSUE THREAD

**Issue by xZeroMCPE** [BukkitPE/BukkitPE#29]
BukkitPE is recuiting developers to help out, With just only 3 devs it won't take us time. So that's why me and my time took some list of people we wanted to join. Please be aware this list will get updated as we found people we think would help out the "team"

Here is the list: 

@applqpak (Joined)
@TonyDroidd (Pending)
@ankitmaharjan252   (Joined)
@Muqsit (Joined)
@AmiroEmad (Joined)
@TheKnightGamer (Joined)
@Driesboy (Joined)
@HypertextPP (Pending)

You will recieve a invitation via email (from github) to join the BukkitPE team you may accept or deny it.

**Comment by applqpak** [comment]
Ok, sure.

**Comment by ankitmaharjan252** [comment]
Gonna get new friends

**Comment by DelxHQ** [comment]
Welcome to the team @applqpak!

**Comment by MiroTheSuperDev** [comment]
i just joined thx @AndreTheGamer 

i am good in website coding and xenforo managing

i made mcrafters forums http://mcrafters.ml

@applqpak can prove that

**Comment by xZeroMCPE** [comment]
@AmiroEmad Nice to know :)

**Comment by DelxHQ** [comment]
Welcome @AmiroEmad!

**Comment by MiroTheSuperDev** [comment]
guys i have exams so i will be inactive for a while

**Comment by xZeroMCPE** [comment]
Alright, do well on the exam ;)

**Comment by Muqsit** [comment]
I would love to join in, but I am just a beginner in this field, but I can still help >:)

**Comment by ghost** [comment]
I am a beginner too. You can join.

**Comment by ghost** [comment]
I've sent invitation to you accept it. :)

**Comment by Muqsit** [comment]
=D

**Comment by ghost** [comment]
Welcome to the team @Muqsit :)

**Comment by MiroTheSuperDev** [comment]
Guys don't make everyone owner unless your sure he is trusted

**Comment by MiroTheSuperDev** [comment]
We can give member write access but admin access isn't a good idea for new members

**Comment by xZeroMCPE** [comment]
@AmiroEmad Good point. I've just gave everybody here "Member" access. The only owners/i trusted with Owner access is @DelxHQ , @AmiroEmad @ankitmaharjan252

**Comment by MiroTheSuperDev** [comment]
their permission should be write not read

because read doesnt have any difference between member and non member

also if someone tried to destroy the project using his write permissions we can easily revert his commits

**Comment by xZeroMCPE** [comment]
@AmiroEmad Just did that! xD

**Comment by ghost** [comment]
I may be happy to join BukkitPE.

**Comment by dries-c** [comment]
i will!

**Comment by ghost** [comment]
@TheKnightGamer you have been invited

**Comment by MiroTheSuperDev** [comment]
guys i will be inactive for a moment

**Comment by xZeroMCPE** [comment]
@AmiroEmad  Alright.

**Comment by dallinac** [comment]
Can I help?

**Comment by ghost** [comment]
All software will go down because of Microsoft

**Comment by dallinac** [comment]
@TheKnightGamer ? Are you talking about the latest Minecraft PE update with realms? Becuase that certainly will not be the downfall of Minecraft PE servers since not everyone wants to pay for reams..

**Comment by ghost** [comment]
Why?

**Comment by dallinac** [comment]
Thanks for deleting my comment...

**Comment by dries-c** [comment]
?

**Comment by MiroTheSuperDev** [comment]
guys there is a problem i dont know java so i may have to learn it .
