### ISSUE TITLE
.Phar

### ISSUE THREAD

**Issue by Erkam246** [BukkitPE/BukkitPE#3]
can i have a phar file of this or can i make that self?

**Comment by xZeroMCPE** [comment]
You can download a complete zip file of BukkitPE it includes the phar and starting script to start the server here: https://github.com/BukkitPE/BukkitPE/releases/download/1.0.0/BukkitPE.zip

Also, please next time read the main page. There should be some info there :) 

Main page: https://github.com/BukkitPE/BukkitPE

**Comment by Erkam246** [comment]
ok
