### ISSUE TITLE
Not giving credit

### ISSUE THREAD

**Issue by legoboy0215** [BukkitPE/BukkitPE#30]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - Please make sure you check
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------
  This project did not give credit to PocketMine-MP at ALL. You did not write the base.

**Comment by xZeroMCPE** [comment]
@legoboy0215  This project is still in beta, We have not finished the readme.md we are working on rewriting it... We will provide credits :)
