### ISSUE TITLE
Are popups broken?

### ISSUE THREAD

**Issue by DelxHQ** [BukkitPE/BukkitPE#35]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

Are the Popups broken?

**Comment by dries-c** [comment]
no only tips down work

**Comment by DelxHQ** [comment]
Popups are broken in BukkitPE! My plugins dont seem to be sending them

**Comment by xZeroMCPE** [comment]
@DelxHQ  Popups are not broken. Only TIPS are.

**Comment by DelxHQ** [comment]
broken, try sending a popup on bukkitpe

**Comment by DelxHQ** [comment]
never mind
