### ISSUE TITLE
Bukkit  in Java

### ISSUE THREAD

**Issue by ghost** [BukkitPE/BukkitPE#36]
Let have another respiratory with a java version of Bulkit for MCPE

**Comment by xZeroMCPE** [comment]
Ya we are porting it as of now. We are just confused when it comes to compilling the jar file

**Comment by DelxHQ** [comment]
@AndreTheGamer get on kik

**Comment by ghost** [comment]
I may help you guys I know Java a lot.

**Comment by xZeroMCPE** [comment]
@TheKnightGamer  https://github.com/BukkitPE/Porting help us there

**Comment by ghost** [comment]
I with be helping soon.

**Comment by xZeroMCPE** [comment]
Porting has been complete and it sync on the main repo..  We've deleted https://github.com/BukkitPE/Porting since it's no longer needed!
