### ISSUE TITLE
Please don't remove copyright notice from copylefted source

### ISSUE THREAD

**Issue by fromgate** [BukkitPE/BukkitPE#39]
Hello!

I'm contributor of [Nukkit project](https://github.com/Nukkit/). And I find that copyright information about former authors was removed from this fork of Nukkit server software. 

You removed information about former authors from source code and did not left any information about former project in the readme file. 

I created a class ConfigSection from the scratch and I was surprised to find this class in "your" project with removed information about authors. Compare: [Nukkit ConfigSection](https://github.com/Nukkit/Nukkit/blob/master/src/main/java/cn/nukkit/utils/ConfigSection.java#L5-L7) and [BukkitPE ConfigSection](https://github.com/BukkitPE/BukkitPE/blob/master/src/main/java/net/BukkitPE/utils/ConfigSection.java#L5-L7).  

Nukkit is released under GPL, but it doesn't means that you now can take over ownership and release it under new name without information about former project and former authors.

Please fix it and put add information that your project is based on Nukkit.

**Comment by xZeroMCPE** [comment]
Credit will be given
