### ISSUE TITLE
BukkitPE.jar

### ISSUE THREAD

**Issue by MaryVictoria** [BukkitPE/BukkitPE#4]
can i have on this?

**Comment by xZeroMCPE** [comment]
BukkitPE isn't a jar file.... Instead it's a .phar file
Look here for downloads: https://github.com/BukkitPE/BukkitPE/releases

**Comment by MaryVictoria** [comment]
or do u have support in java?

**Comment by xZeroMCPE** [comment]
We only have support in PHP, But anyway we are planning of adding support in JAVA, Use the one we have right now as it's stable and fast with ultra features ;)

**Comment by MaryVictoria** [comment]
okay thanks

**Comment by fromgate** [comment]
@MaryVictoria 
You're not only one who have been deceived by the name of project.

Bukkit is name of great Java API and using this name for fork of php clone of pocketmine is shaming someone who did it.

@MaryVictoria if you interesting in server platform for MCPE based on Java you must check the Nukkit project :)

**Comment by JCDcrafter** [comment]
Has java been added yet or is there a planned date yet?

**Comment by xZeroMCPE** [comment]
We are migaring to java in the backgrond. You won't see any progress here on out github page. We will upload the first release and switch to it when we get it ready for you guys :) Should take 1-3 days or more.

**Comment by JCDcrafter** [comment]
Do you mean you are switching?
BukkitPE PHP5
BukkitPE PHP7
BukkitPE JAVA
Which one's are you keeping out of those?

**Comment by xZeroMCPE** [comment]
@JCDcrafter  We are switching to "BukkitPE Java" We will no longer be using PHP. The PHP7 branch was created since some users who are still be using BukkitPE (php version) wanted the php7 version. Although as soon we've switched to Java all the php's version of BukkitPE will be removed and will be replaced with the java version.

**Comment by JCDcrafter** [comment]
Are you 100% sure you will be able to get java? As I read in another forum this: 'We were thinking to use it java but after creating jar it was not working. So, we get back to php.' From one of your staff and I think using bukkit plugins for MCPE is the best idea ever! Keep up the good work ☺

**Comment by DelxHQ** [comment]
Yes. We will be able to get Java working.

**Comment by JCDcrafter** [comment]
Any idea how long it may take?

**Comment by xZeroMCPE** [comment]
@JCDcrafter  Some days (1-2), i'm already working on it as of now in the background. When i feel like to. I"ll maybe release a beta build /upload all project files on github. But again only problem i may encounter is compilling the jar file. But ill use my friend to search it up which is "Google" :P
