### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Snake1999** [BukkitPE/BukkitPE#41]
?

**Comment by xZeroMCPE** [comment]
Credit will be given

**Comment by Pub4Game** [comment]
I've always hated such people who steal the work of others. You understand that team Nukkit worked on this for a year? According to your changes, I see that Java you did not know and steal change from Genisys and us.

**Comment by fromgate** [comment]
Fantastic. Are you sure it's a good way of discussion to remove original message?
Good job.

**Comment by ProjectInfinity** [comment]
"AndreTheGamer changed the title from Alert: remove all codes unlicensed or disallowed to copy by our Nukkit team. to ? 5 hours ago" LOL. Good job. You have zero credibility @AndreTheGamer

**Comment by xZeroMCPE** [comment]
@ProjectInfinity @fromgate @Pub4Game @Snake1999   I'm very sorry for what i did. I felt bad knowing/thinking about it. Anyway credits is given on the Readme.md and all original credits will be restored on the source itself. Thank you and again i'm very sorry.

**Comment by Snake1999** [comment]
Then do it now. Rename back everything in your code. Add the origin in your LGPL license copy. Add all our contributors in your contributior list. Or take your DMCA takedown.
Action speak louder than words.

**Comment by ifvictr** [comment]
@AndreTheGamer You really want to make your own server software, don't you? Well, sorry to tell you, buddy, but forking other's software and renaming everything isn't the way to do it.
