### ISSUE TITLE
Jenkins and 0.15.0

### ISSUE THREAD

**Issue by JCDcrafter** [BukkitPE/BukkitPE#42]
Jenkins is down for BukkitPE and I need jar for 0.15.0 have you got it yet?i

**Comment by xZeroMCPE** [comment]
@JCDcrafter Jenkins seems to be down :/ 
I'm working as of now to fix it :)

**Comment by ghost** [comment]
We do not support 0.15.0 right now but It will be supported later

**Comment by Pub4Game** [comment]
@JCDcrafter Easier to use [Nukkit](https://github.com/Nukkit/Nukkit), because all fixes will be taken from there.

**Comment by JCDcrafter** [comment]
@Pub4Game Yeah ik about Nukkit but I cannot find a compiled jar ATM for 0.15.0 which works for the host that I am using as the official jars on Nukkit's website work perfectly

**Comment by xZeroMCPE** [comment]
@JCDcrafter  Our jenkins is up! sorry for the delay. There was an issue with the installation causing some builds to fail but its all fixed.
