### ISSUE TITLE
Forums nulled?

### ISSUE THREAD

**Issue by Vaults1** [BukkitPE/BukkitPE#43]
Hello, I have a suspicion that the forums are nulled, could someone please clarify yes or no and provide proof. Thanks!

**Comment by xZeroMCPE** [comment]
No, we are not using a nulled version of the forum.  Paying 140$ + XenForo Resource Manager - $60\*  is something i can afford myself.

**Comment by k3ithos** [comment]
I can clarify that myself. It has clearly come to my attention that the forums are indeed nulled. The copyright link is not working and does not link to XenForo's home page. @AndreTheGamer, would you like to provide proof for your argument of using a legitimate version of XenForo for BukkitPE?

**Comment by xZeroMCPE** [comment]
@keithkfng  Sure,

Here is our Validation Token which can be checked if we are nulled or legit. 

033a03afaa90187b960bef838be9f8ff

**Comment by k3ithos** [comment]
@AndreTheGamer your token is legit, but your version is not. The token doesn't match the domain either. So you've stolen it, haven't you?
![image](https://cloud.githubusercontent.com/assets/13236085/16169953/7b3757ae-3584-11e6-899b-4e2d3fcfab94.png)

**Comment by xZeroMCPE** [comment]
@keithkfng Why would i steal licenses. I bought it off http://www.mc-market.org/  it isn't linkedto Forums.BukkitPE.net
