### ISSUE TITLE
No download link or method

### ISSUE THREAD

**Issue by djpiper28** [BukkitPE/BukkitPE#48]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------
  You can't download the latest build from travis-ci. As such I recommend setting up circle-ci (which can use travis-ci set-up files) then use the artifact link for downloads.

By the way the owner must do it.

**Comment by djpiper28** [comment]
I know that there is jenkins but if that fails then we could always have a backup.

**Comment by xZeroMCPE** [comment]
@djpiper28 Yea, true. I made a sub-domain and added a script in there that downloads the lastest BukkitPE jar and place it there. 

It's Downloads.BukkitPE.net/Latest.jar 

It will get updated by itself.
