### ISSUE TITLE
Example Plugin

### ISSUE THREAD

**Issue by xZeroMCPE** [BukkitPE/BukkitPE#50]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

I think we should submit a first plugin to BukkitPE forums plugin section. It seems empty

**Comment by djpiper28** [comment]
We need to get this on http://ci.mengcraft.com:8080/job so that my pom.xml file for iplogger works [https://github.com/djpiper28/iplogger](https://github.com/djpiper28/iplogger)

**Comment by xZeroMCPE** [comment]
@djpiper28 Seems to be down
