### ISSUE TITLE
15.0 Update

### ISSUE THREAD

**Issue by xZeroMCPE** [BukkitPE/BukkitPE#51]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - Please make sure you check
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------
  15.0 been out a few weeks ago, i'm thinking of updating BukkitPE to 15.0 Any help is needed :)

**Comment by djpiper28** [comment]
I've done some work on 0.15.0

**Comment by xZeroMCPE** [comment]
@djpiper28 Alright great

**Comment by ekids9702122935** [comment]
Can anyone please tell me how to upgrade the server to 0.15.0  version??

**Comment by Super35** [comment]
0.15 protocol is 81 api --> 2.0.0 @AndreTheGamer

**Comment by xZeroMCPE** [comment]
@djpiper28 started updating it but he went dead.

I don't have time to update it. I will as soon as i'm home from vacation!

**Comment by Super35** [comment]
Is this chat getting labeled or not

**Comment by Super35** [comment]
New Update : 0.15.4 protocol 82 api is still 2.0.0

**Comment by Super35** [comment]
ITXTech / Genisys is already done with 0.15.4 (exampleservers) CookieBuild

**Comment by xZeroMCPE** [comment]
ok

**Comment by Super35** [comment]
do you need a 0.15.4 pocketmine.yml ?

**Comment by Super35** [comment]
Because i can help

**Comment by xZeroMCPE** [comment]
BukkitPE is not "pocketmine". It's written in JAVA! If you are wanting to help update it to 15.4 go for it! :)

**Comment by djpiper28** [comment]
We could port genysis directly to java and mod the functions to allow nukkit plugin compatibility

**Comment by xZeroMCPE** [comment]
Yea, we should do it.

**Comment by TheProest35YT** [comment]
Genisys has a java one its Nemisys but its failing
