### ISSUE TITLE
how

### ISSUE THREAD

**Issue by majovec** [BukkitPE/BukkitPE#55]
How to instal on linux (vps )

**Comment by xZeroMCPE** [comment]
Download the jar file from our jenkins

Then after you can run the jar using

`java -jar JAR-NAME-Here`

To make it easy to use just rename the jar to BukkitPE then run it using the same command above but replace the BukkitPE-1.0-SNAPSHOT.jar with the actual jar name! :+1:

**Comment by majovec** [comment]
and is funcion bukkit or
 spigot plug ?

**Comment by xZeroMCPE** [comment]
@majovec  what?

Also head over to our gllitter chat ;) 

its more faster!
