### ISSUE TITLE
Install Problem

### ISSUE THREAD

**Issue by ghost** [BukkitPE/BukkitPE#6]
Hi

i want install BukkitPE to test on my Window PC

i download BukkitPE.zip  ,Phar.zip and Bin.zip on BukkitPE Release 0.13.x

i extrakt BIN and extrakt BukkitPE / Phar in the BIN Folder.
cmd and > start -> Enter
another Console Windows open .... nothing no Script start like Pocketmine

new 

Error

/usr/bin/php/php.exe: error while loading shared libraries: MSVCR110.dll: cannot open shared object file: No such file or directory
bin\php\php.exe: Exit 127

why ?   thx

**Comment by xZeroMCPE** [comment]
Download  Microsoft Visual C++ Redistributable  search that on google. After server should work

**Comment by ghost** [comment]
I have it download to my raspberry pi2
When i Start in Console Start.sh   

./Start.sh     i become error   no permission

**Comment by DelxHQ** [comment]
Run this command in your SSH: chmod +x start.sh

**Comment by ghost** [comment]
couldnt find a workin PHP Binary.
i have copy the same bin folder in the BukkitPE Folder like on the Windows Server .

**Comment by DelxHQ** [comment]
Your using the windows bin. You must use the linux bin!

**Comment by ghost** [comment]
on github is only a Windows BIN !??
can i use the Bin from Pocketmine ?

**Comment by DelxHQ** [comment]
Yes.

**Comment by ghost** [comment]
it works ! BIG THX !!!

The Animals Spawn but not Walk.
AI not inplented

one the first page of Github stand     "Mob AI including Animals" !??

**Comment by DelxHQ** [comment]
We haven't yet added the AI yet.

**Comment by ghost** [comment]
ok !
When did you install it before ?
I'm sorry that I ask so stupid !!!
1 Day - 1Week 1 Month 1 Year ?

thanks from Austria

**Comment by DelxHQ** [comment]
Install what?

**Comment by ghost** [comment]
AI

**Comment by DelxHQ** [comment]
We don't install the AI we code it into the BukkitPE core. I am now closing this issue. From then you will not be able to reply.

**Comment by xZeroMCPE** [comment]
Mobs AI is being work on, Please create a new issue base on us adding MOBS AI thanks, Isuue has been closed
