### ISSUE TITLE
make genisys in java 

### ISSUE THREAD

**Issue by dries-c** [BukkitPE/BukkitPE#65]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

**Comment by ghost** [comment]
You mean take/copy code from genisys and convert it into java?

**Comment by dries-c** [comment]
yes

**Comment by ghost** [comment]
What feature you want from genisys?

**Comment by dries-c** [comment]
All

Op 10-aug.-2016 17:05 schreef "Ankit" notifications@github.com:

**Comment by ghost** [comment]
We can't convert the whole project into java cause it is hard as well as it will take a long time.

**Comment by dries-c** [comment]
why not

**Comment by xZeroMCPE** [comment]
Will take alot of them, and we"ll need more help then we need :+1:

**Comment by Aericio** [comment]
Make CPU explode in Java?

**Comment by ghost** [comment]
I'm working on ai from genisys

**Comment by lavender-sys** [comment]
Don't convert the code. Genisys is messy and buggy. Make it from scratch!

**Comment by ghost** [comment]
Okay! BTW i need help on this. Anyone there to help me.
