### ISSUE TITLE
EntityDamageEvent error

### ISSUE THREAD

**Issue by grzegorz2047** [BukkitPE/BukkitPE#67]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  ## **START ISSUE STATEMENT BELOW**<br>
  
  I'm writing a plugin for my server and when I try to use EntityDamageEvent I get
  http://pastebin.com/QqsxTcek
  I tried with method without any code inside and it throws the same error:
  
  @EventHandler
    public void onDamage(EntityDamageEvent e) {
  
    }
  Maybe it throws without even listening those events, I don't know.
  Code seems to execute, but It should be fixed. 
  Also why EntityDamageEvent triggers when player is in creative mode?
  And when I walk into lava I get http://pastebin.com/krmX2Y6h error

**Comment by xZeroMCPE** [comment]
What are you trying yo do with it?

**Comment by grzegorz2047** [comment]
@xZeroMCPE  I'd like to cancel damage when player gets hit or receives any damage from falling and etc.

**Comment by xZeroMCPE** [comment]
@grzegorz2047  Can you paste bin part of the code? (source)

**Comment by grzegorz2047** [comment]
In main file I register listener:
Server.getInstance().getPluginManager().registerEvents(new AttackListeners(), this);
and AttackListener is here:
http://pastebin.com/KuevVHt9

**Comment by xZeroMCPE** [comment]
Seems like you aren't doing something wrong or messing an import statement.

**Comment by grzegorz2047** [comment]
@xZeroMCPE I use latest build of BukkitPE. When there is no plugin everything seems to be fine. Also when AttackerListener class is completely empty also doesn't produce any errors. So it has to be something when bukkitpe gets info about listening EntityDamageEvent and simmilar Damage Events.
Also I use Latest Minecraft Win 10 pocket edition and MC:PE for android v0.15.6

**Comment by xZeroMCPE** [comment]
@grzegorz2047  Does it cancel the PVP damage? but still gives error or it doesn't work and it logs errors? I think i may know what's wrong..

**Comment by grzegorz2047** [comment]
@xZeroMCPE It doesn't cancel fall damage, it logs error and prints my debug msg "Wykonalem event!"
here is my current code: http://pastebin.com/sUDFcTju
You can reproduce it, download latest build, use v1.15.6 MCPE client, register EntityDamageEvent, and try to jump off to get damage. 
EDIT: It cancels damage, but it gives hit sounds and hit effects.
EDIT2: Here are some logs about it: http://pastebin.com/NM9Fivxt

**Comment by xZeroMCPE** [comment]
Yeah, i got it. Should be fixed by today or tomorrow.

**Comment by TheDiamondYT1** [comment]
Blame Nukkit

**Comment by grzegorz2047** [comment]
Is there any progress with it?

**Comment by xZeroMCPE** [comment]
Yeah, i'm currently rewriting it.

EDIT: i closed this my mistake.

**Comment by grzegorz2047** [comment]
Ok, let me know when once it's finished.

**Comment by xZeroMCPE** [comment]
Okay, will do.

**Comment by xZeroMCPE** [comment]
Hey, head over to our jenkins and download a dev build. Test it out

**Comment by TheDiamondYT1** [comment]
No coz this is bs

**Comment by grzegorz2047** [comment]
I dont see any changes towards fixing this issue, but if you say it might be fixed ill check it out

**Comment by grzegorz2047** [comment]
Error still occurs: http://pastebin.com/u91EShDN

**Comment by xZeroMCPE** [comment]
Whoops, forgot. Will be working on it!

**Comment by grzegorz2047** [comment]
@xZeroMCPE Great.
