### ISSUE TITLE
QueryRegenerateEvent doesn't manipulate server data

### ISSUE THREAD

**Issue by grzegorz2047** [BukkitPE/BukkitPE#68]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

When I try to use QueryRegenerateEvent and change few things "on fly", I can't do it. it changes numOfPlayers, maxPlayers but it doesn't change motd.
Here is my code:  
http://pastebin.com/hDK5vuEU

**Comment by xZeroMCPE** [comment]
Hmn

**Comment by xZeroMCPE** [comment]
It should be

`event.setName("test");`

Or

`event.getServer().getNetwork().setName("test");`

**Comment by grzegorz2047** [comment]
@xZeroMCPE Oh, okey, this API is bit tricky, wouldn't be easier just setMotd("test")? xd Lack of documentation makes hard to use API.
event.setName("test"); doesn't exist in this event, that's why  it confused me and didn't work xd
Server.getInstance().getNetwork().setName("test"); seems to work.
Also I see that it changes with delay ~30 seconds to refresh after server start.

**Comment by xZeroMCPE** [comment]
@grzegorz2047 Yeah, i completely understand. Making a API doc would be useful so developers can learn it at ease.

But anyway's wouldn't that take a long time? 

And it has a delay to prevent malfunctions. But i'm sure that isn't a problem?

**Comment by grzegorz2047** [comment]
No, it isn't a problem if it happens on server start, but I would like to make dynamic motd, so it can show current status of server.

**Comment by xZeroMCPE** [comment]
Try adding it to a task. It would be better...

**Comment by xZeroMCPE** [comment]
EDIT: You can view our plugin tut [here](https://forums.bukkitpe.net/index.php?threads/plugin-tutorial-bukkitpe-java.107)

**Comment by grzegorz2047** [comment]
@xZeroMCPE I don't need this tut, because there are basics of basics xd 
I need to change thinking from TCP to UDP xd I mean try to understand, that it works differently not exacly like PC version.
Anyway in this event you should add event.setName(); method, because it doesn't exist and you have to go through server->network->setname to change motd.

**Comment by xZeroMCPE** [comment]
Yeah, i understand. I"ll think about that!

**Comment by xZeroMCPE** [comment]
@grzegorz2047  Hey, make sure your BukkitPE is up to date! I've added a few more things to make it more easily :)

**Comment by grzegorz2047** [comment]
@xZeroMCPE It's great to hear that you added missing motd stuff. It will no longer make problems. Keep it up improving, because this can be even better than fork of PocketMine in java called Nukkit.
