### ISSUE TITLE
API DOCS suggestion

### ISSUE THREAD

**Issue by grzegorz2047** [BukkitPE/BukkitPE#69]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

You could auto generate API documentation (javadocs) as bukkit did through comments for example: https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/entity/EntityPortalEvent.java
or here:
https://github.com/Bukkit/Bukkit/blob/master/src/main/java/org/bukkit/event/entity/EntityDeathEvent.java
here is generated doc: https://jd.bukkit.org/index.html?org/bukkit/event/entity/EntityDeathEvent.html
You could auto generate on jenkins somehow and it would bring more devs to BukkitPE.
Also you could post auto-generated docs on website and It would be cool. Of course it need a little more work when you add new API features, but It pays off at the end.
Example generated doxygen site:
http://bukkit.luricos.de/api/1.7.9-R0.2/d7/dd9/namespaceorg_1_1bukkit.html
and classic version:
https://jd.bukkit.org/
So IMO it shouldn't take much more time to make it work

**Comment by xZeroMCPE** [comment]
Thanks for the suggestions! 

I'm currently working on a Developer Hub it"ll have resources for developers such as jds, jenkins server link, github ect. You can preview it at

[dashboard.bukkitpe.net](http://dashboard.bukkitpe.net)

EDIT: JavaDocs has been added! Just visit the dashboard and click "Java Docs" and it"ll send you to the page!

**Comment by grzegorz2047** [comment]
If this developer hub will be linked on main site it would be useful for sure.

**Comment by grzegorz2047** [comment]
ech, misclick xd This dev hub is simple and should be ok for now. Also it should be linked on main site when it's finished. Also it would probably need update main site to look less like every pocketmine fork.
You can take inspiration from https://hub.spigotmc.org/

**Comment by xZeroMCPE** [comment]
Alright, i"ll see what i can do.

**Comment by BuddyAW** [comment]
is there a way to get the plugin dev to work on eclipse when i start off with the tutoral i get so many errors

**Comment by grzegorz2047** [comment]
@BuddyAW What kind of errors do you have?
@xZeroMCPE I see you added Javadocs :+1:  Also when I go to the page https://dashboard.bukkitpe.net/
I see website without css formatting.

**Comment by xZeroMCPE** [comment]
@grzegorz2047 Fixed, the css formatting should work now :)

**Comment by BuddyAW** [comment]
i cant like export the file out as a jar

**Comment by xZeroMCPE** [comment]
@grzegorz2047  Which ide are you using?

**Comment by BuddyAW** [comment]
eclipts i keep getting errors from netbeans

**Comment by xZeroMCPE** [comment]
Show me the error logs

**Comment by BuddyAW** [comment]
The package containing the class javax.swing.JComponentBeanInfo was not loaded
thats when it first starts up

**Comment by BuddyAW** [comment]
i am running ubuntu rn btw

**Comment by xZeroMCPE** [comment]
The problem isn't BukkitPE it's a class related to your plugin. Try to remove it
