### ISSUE TITLE
Plugins 

### ISSUE THREAD

**Issue by ghost** [BukkitPE/BukkitPE#7]
In the game is no Weather or AI Mobs 

There is a plugin to install ?
Pocketmine plugins Not Work

**Comment by xZeroMCPE** [comment]
We will be adding a website soon, On which where you will be able to download plugins from: www.BukkitPE.net as of now please contract the plugin dev to upgrade their API to the one BukkitPE uses. 

For the whether you will need to go in-game and use /weather rain and goto the BukkitPE.yml and enabled weather.

**Comment by DelxHQ** [comment]
The weather should toggle automatically.

**Comment by dries-c** [comment]
use .tk its free

**Comment by ghost** [comment]
.tK ???

**Comment by dries-c** [comment]
yes

**Comment by dries-c** [comment]
domain

**Comment by ghost** [comment]
Www. Bukkitpe.tk  ?

**Comment by xZeroMCPE** [comment]
We will used a Pay domain such as "BukkitPE.net it should be added today :) i will notify you guys.

**Comment by xZeroMCPE** [comment]
Visit our site: www.BukkitPE.net  then click forum or plugins, you can also registered.

**Comment by dries-c** [comment]
worked

**Comment by dancing-ipsum** [comment]
is there plugin documentation?

**Comment by xZeroMCPE** [comment]
Yep, here https://github.com/BukkitPE/Plugin-Documentation
You can submit plugins via our forum at > forums.bukkitpe.net

Also, BukkitPE has the same APIas pocketmine, but instead of using 

```
use pocketmine/
```

**_You will need to use**_

```
use BukkitPE/
```

**Comment by dancing-ipsum** [comment]
ooh ok

**Comment by MiroTheSuperDev** [comment]
api 2.0.0 right?

**Comment by xZeroMCPE** [comment]
No, we aren't using PHP7 but we are planing on upgrading to it soon. Anyway default api is 1.13.2
