### ISSUE TITLE
start up

### ISSUE THREAD

**Issue by BuddyAW** [BukkitPE/BukkitPE#71]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

this keeps comeing up

Exception in thread "main" java.lang.UnsupportedClassVersionError: net/BukkitPE/BukkitPE : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
    at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by ankitmaharjan252** [comment]
Any plugins?

**Comment by ghost** [comment]
That might be an error of plugin cause i've tested with latest build of BukkitPE (without any plugins) but works fine.

**Comment by BuddyAW** [comment]
can you send a copy all what i need

**Comment by BuddyAW** [comment]
btw i am useing lunix

**Comment by ghost** [comment]
First remove or create new folder named something you like eg: BukkitPE
Download this (latest one): http://jenkins.bukkitpe.net:8080/job/BukkitPE/lastSuccessfulBuild/artifact/
Move/Copy that and paste it into new folder
download or copy start.sh and run it

**Comment by BuddyAW** [comment]
still the same error and i only hae to bukkitpe.jar and start.sh in there and it is still crashing

**Comment by xZeroMCPE** [comment]
Try to remove all files, such as BukkitPE.yml ect.

Only leave BukkitPE.jar and the start.sh  then after start server to test

**Comment by BuddyAW** [comment]
thats all that is in there

**Comment by BuddyAW** [comment]
can you

**Comment by BuddyAW** [comment]
send me the start.sh

**Comment by xZeroMCPE** [comment]
Show me a picture of your workplace ect

**Comment by xZeroMCPE** [comment]
Sure

https://raw.githubusercontent.com/BukkitPE/BukkitPE/master/start.sh

**Comment by BuddyAW** [comment]
![screenshot from 2016-08-30 11 41 35](https://cloud.githubusercontent.com/assets/9854308/18096023/d5951bb8-6ea6-11e6-8974-d14f484a839b.png)

**Comment by xZeroMCPE** [comment]
Try to update your java

**Comment by BuddyAW** [comment]
can you send the commoand to do that

**Comment by xZeroMCPE** [comment]
What OS are you running? and 32bit or 64bit

**Comment by BuddyAW** [comment]
lunix mint and 32 bit

**Comment by xZeroMCPE** [comment]
Run those commands on the terminal

```
add-apt-repository ppa:webupd8team/java

apt-get update

apt-get install oracle-java8-installer
```

**Comment by BuddyAW** [comment]
same error

**Comment by xZeroMCPE** [comment]
Hmn, try to reboot your machine

**Comment by BuddyAW** [comment]
i did

**Comment by BuddyAW** [comment]
2 time

**Comment by xZeroMCPE** [comment]
Head over to our Gitter  chat.

**Comment by BuddyAW** [comment]
weres that

**Comment by xZeroMCPE** [comment]
https://gitter.im/BukkitPE/BukkitPE

**Comment by BuddyAW** [comment]
anyone got any other answers

**Comment by xZeroMCPE** [comment]
I've tested it on Ubuntu 14 (via ssh) seems to work fine!

https://gyazo.com/834c856b8e84687a89c1e2157ea952d6

**Comment by BuddyAW** [comment]
i am useing lunix mint 
https://linuxmint.com/download.php

**Comment by xZeroMCPE** [comment]
Do you have the lastest version of JAVA installed? 

type "java version" on terminal or "java -version" and tell me what it says!

**Comment by BuddyAW** [comment]
lol i got it to work do you guys know when they will be doing a new update beacsue  of mc is out i havent installed it yet but i am looking through the changlogs 
all that is new is a new thig about texterpacks and bugs fixes so the normal stuff

**Comment by xZeroMCPE** [comment]
We"ll update BukkitPE to 16.0 when it has been _global_ release. Which means that it should be out for androids, ios ect! 

Untill then, we"ll work on the branch so when its' released, BukkitPE will be ready!
