### ISSUE TITLE
When I try joining it says unable to connect to world

### ISSUE THREAD

**Issue by matt11matthew** [BukkitPE/BukkitPE#75]
When I try joining it says unable to connect to world
I've tried every version I've even compiled the latest version
I can see the MOTD but it wont let me join 
I've tried everything

**Comment by xZeroMCPE** [comment]
Is the server port-forwarded?

**Comment by matt11matthew** [comment]
I haven't checked

**Comment by matt11matthew** [comment]
Checking

**Comment by matt11matthew** [comment]
It's not a config option. I'm trying to develop plugins locally

**Comment by xZeroMCPE** [comment]
You sure your MCPE is updated?

**Comment by matt11matthew** [comment]
It is I had to compile my own version because the download link was broken

**Comment by matt11matthew** [comment]
It just wont let me join

**Comment by matt11matthew** [comment]
When it's offline I get server is full

**Comment by xZeroMCPE** [comment]
Try restarting the device the server is hosted on

**Comment by matt11matthew** [comment]
I tried

**Comment by matt11matthew** [comment]
It's not a port issue with windows 10 version I tried mobile

**Comment by matt11matthew** [comment]
Versions are fine

**Comment by matt11matthew** [comment]
The motd pings fine
https://gyazo.com/2da49659b842074050934b1f53419add

but when I try to join
https://gyazo.com/596465d0380e9a883b049aae86392b65

**Comment by xZeroMCPE** [comment]
Windows?

**Comment by matt11matthew** [comment]
Windows 10 MCPE
My os is Windows 10

**Comment by xZeroMCPE** [comment]
Method 1: PowerShell (credits to @robske110)

Open Windows PowerShell and run the following command: 

CheckNetIsolation LoopbackExempt -a -n="Microsoft.MinecraftUWP_8wekyb3d8bbwe" 

When you next open the game, you should be able to connect to your local server. If not, try the second method.

**Comment by matt11matthew** [comment]
What is the second method?

**Comment by xZeroMCPE** [comment]
Method 2: Modify your options.txt (credits to @timm1292)
1. Navigate to %localappdata%\Packages\Microsoft.MinecraftUWP_8wekyb3d8bbwe\LocalState\games\com.mojang\minecraftpe. 
2. Open the options.txt in a text editor and find the option dev_uselocalserver. Set it to 1 and save the file. 
3. Restart your game and attempt to connect to your server.

**Comment by matt11matthew** [comment]
On windows 10?

**Comment by xZeroMCPE** [comment]
Yes

**Comment by matt11matthew** [comment]
Nope

**Comment by matt11matthew** [comment]
Wont work

**Comment by xZeroMCPE** [comment]
What won't work?

**Comment by matt11matthew** [comment]
Joining

**Comment by matt11matthew** [comment]
The MOTD shows

**Comment by matt11matthew** [comment]
It just wont let me join

**Comment by matt11matthew** [comment]
It doesn't call prelogin event

**Comment by matt11matthew** [comment]
So it's not whitelist/ban/etc

**Comment by xZeroMCPE** [comment]
Try joining through the EXTERNAL Server. Don't click the LAN server

**Comment by matt11matthew** [comment]
I tried

**Comment by matt11matthew** [comment]
Both don't work

**Comment by xZeroMCPE** [comment]
try resetting your players/ folder along with server settings

**Comment by matt11matthew** [comment]
Already tried

**Comment by xZeroMCPE** [comment]
Same thing happened with a different server software?

**Comment by matt11matthew** [comment]
No

**Comment by matt11matthew** [comment]
It's not a java issue

**Comment by xZeroMCPE** [comment]
try setting up a clean installation of BukkitPE. on a another server and see if it works.

**Comment by matt11matthew** [comment]
I said I tried that

**Comment by matt11matthew** [comment]
# Advanced configuration file for BukkitPE

# Some of these settings are safe, others can break your server if modified incorrectly

# New settings/defaults won't appear automatically on this file when upgrading.

settings:
 #Multi-language setting
 #Available: eng, chs, cht, jpn, rus, spa, pol, bra, kor
 language: "eng"
 #Whether to send all strings translated to server locale or let the device handle them
 force-language: false
 shutdown-message: "The server is closed"
 #Allow listing plugins via Query
 query-plugins: true
 #Show a console message when a plugin uses deprecated API methods
 deprecated-verbose: true
 #Number of AsyncTask workers
 #If set to auto, it'll try to detect the number of cores (and at least 4)
 async-workers: auto

network:
 #Threshold for batching packets, in bytes. Only these packets will be compressed
 #Set to 0 to compress everything, -1 to disable.
 batch-threshold: 256
 #Compression level used of Zlib when sending batched packets. Higher = more CPU, less bandwidth usage
 compression-level: 7
 #Use AsyncTasks for compression. Adds half/one tick delay, less CPU load on main thread
 async-compression: false

debug:
 #If > 1, it will show debug messages in the console
 level: 1
 #Enables commands: /status /gc
 commands: false

level-settings:
 #The default format that levels will use when created
 default-format: mcregion
 #Automatically change levels tick rate to maintain 20 ticks per second
 auto-tick-rate: true
 auto-tick-rate-limit: 20
 #Sets the base tick rate (1 = 20 ticks per second, 2 = 10 ticks per second, etc.)
 base-tick-rate: 1
 #Tick all players each tick even when other settings disallow this.
 always-tick-players: false

chunk-sending:
 #Amount of chunks sent to players per tick
 per-tick: 4
 #Amount of chunks sent around each player
 max-chunks: 192
 #Amount of chunks that need to be sent before spawning the player
 spawn-threshold: 56
 #Save a serialized copy of the chunk in memory for faster sending
 #Useful in mostly-static worlds where lots of players join at the same time
 cache-chunks: false

chunk-ticking:
 #Max amount of chunks processed each tick
 per-tick: 40
 #Radius of chunks around a player to tick
 tick-radius: 3
 light-updates: false
 clear-tick-list: false

chunk-generation:
 #Max. amount of chunks in the waiting queue to be generated
 queue-size: 8
 #Max. amount of chunks in the waiting queue to be populated
 population-queue-size: 8

ticks-per:
 animal-spawns: 400
 monster-spawns: 1
 autosave: 6000
 cache-cleanup: 900

spawn-limits:
 #Max amount of these entities
 monsters: 70
 animals: 15
 water-animals: 5
 ambient: 15

aliases:
 #Aliases for commands
 #Examples:
 #showtheversion: version
 #savestop: [save-all, stop]

worlds:
 #These settings will override the generator set in server.properties and allows loading multiple levels
 #Example:
 world:
  seed: 404
  generator: FLAT:2;7,59x1,3x3,2;1;decoration(treecount=80 grasscount=45)

 # If you are going to use BungeeCordPE set this to true
 # This option allows players to retain their own IP addresses.
BungeeCordPE: false

**Comment by matt11matthew** [comment]
#Properties Config file
#2016-10-02 02:16:50
motd=BukkitPE Server For Minecraft: PE
server-port=19132
server-ip=0.0.0.0
view-distance=10
white-list=0
announce-player-achievements=on
spawn-protection=16
max-players=20
allow-flight=off
spawn-animals=on
spawn-mobs=on
gamemode=0
force-gamemode=off
hardcore=off
pvp=on
difficulty=1
generator-settings=
level-name=world
level-seed=
level-type=DEFAULT
enable-query=on
enable-rcon=off
rcon.password=
auto-save=on
BungeeCordPE=off
online-mode=off

**Comment by xZeroMCPE** [comment]
This works for me, i've tried it.....

**Comment by matt11matthew** [comment]
It's not letting me join

**Comment by xZeroMCPE** [comment]
Try to port forward the server, and join through the IP

**Comment by matt11matthew** [comment]
The server works

**Comment by matt11matthew** [comment]
How?

**Comment by xZeroMCPE** [comment]
Does it work?

**Comment by matt11matthew** [comment]
The server does
it pings the motd for my client 
but when I try to join
I get 
unable to connect to world

**Comment by xZeroMCPE** [comment]
Have you tried connecting through a different device? like phone, pad, ect (PAD as in IPAD)   :: was too lazy to type the "I"!

**Comment by matt11matthew** [comment]
Yes I tried

**Comment by matt11matthew** [comment]
Still the same issue

**Comment by matt11matthew** [comment]
I can join other servers

**Comment by xZeroMCPE** [comment]
change the server port

**Comment by xZeroMCPE** [comment]
Our jenkins is also up!

Jenkins.BukkitPE.net

**Comment by matt11matthew** [comment]
Thanks I think it's my internet fault I'll just use my vps

**Comment by xZeroMCPE** [comment]
ok
