### ISSUE TITLE
 a swhits for bukkit and spigot plugins to load

### ISSUE THREAD

**Issue by ghost** [BukkitPE/BukkitPE#78]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

pls  add this if can tank you

**Comment by ghost** [comment]
We are planning to add this. We havent started to work on it but we will do it soon! Be patient :)

**Comment by ghost** [comment]
yay

**Comment by grzegorz2047** [comment]
I think we could become more popular if whe implement bukkit api

**Comment by xZeroMCPE** [comment]
Yeah, i'm adding support for that :) 
We just need a few more developers that's willing to assist us!

**Comment by grzegorz2047** [comment]
@xZeroMCPE Well, I was thinking about helping you, but I'm not experienced in mc:pe packets.  To be honest, I was looking for open project where I could contribute somehow. If you still need developer I'd like to help.

**Comment by xZeroMCPE** [comment]
Ah i see, but again, Just try your best :) 

I've invited you into the repo. Goodluck!

**Comment by ghost** [comment]
@grzegorz2047 You are also in Contributor list on Forum

**Comment by grzegorz2047** [comment]
@ankitmaharjan252 @xZeroMCPE Thanks. I have one question. Do you have trello or something where you have columns like TODO INPROGRESS DONE? It would be nice to see what is actually to fix, what the status of specific feature.
Example is here:
https://trello.com/b/sM0TxEu1/civcraft-development

**Comment by ghost** [comment]
@xzeromcpe can i
Y help

**Comment by xZeroMCPE** [comment]
@grzegorz2047 We have not made a TODO list atm, But again your free to make one :)

**Comment by grzegorz2047** [comment]
@xZeroMCPE I can make it, but it only has sense, when more than one person is using it xd It makes project less chaotic. You know, you can read about agile. And we could reanimate gitter xd

**Comment by xZeroMCPE** [comment]
@grzegorz2047 Yeah

**Comment by grzegorz2047** [comment]
@xZeroMCPE Is is possible to talk with you through teamspeak or anything like this? I mean realtime xd

**Comment by xZeroMCPE** [comment]
Yeah on skype: andreleon911

**Comment by ghost** [comment]
@xZeroMCPE can i join this group im not good at java but i can protocals and translated (dutch)
and other stuff

**Comment by xZeroMCPE** [comment]
You can't just change protocols.... sometimes some packets must be changed / added which can sometimes be found here! http://wiki.vg/Pocket_Minecraft_Protocol
