### ISSUE TITLE
Keep getting the same crash.

### ISSUE THREAD

**Issue by meetloaf13** [BukkitPE/BukkitPE#8]
FWIW, I have zero plugins loaded.

[BukkitPE.zip](https://github.com/BukkitPE/BukkitPE/files/116910/BukkitPE.zip)

**Comment by xZeroMCPE** [comment]
Can you show me what's causing the crash? Let me see the crashdump or console log

**Comment by meetloaf13** [comment]
Andre,  this happened about every 90 minutes all day yesterday.  To my knowledge every single time it happened without a player having been connected. I'm sure it happened all night again. . It is the same error that you linked. . I included 3 crash dumps in my OP .

**Comment by MunkySkunk** [comment]
I am getting this whether there is a user logged in or not and happens about every 30 mins.

**Comment by meetloaf13** [comment]
Mine happened every 90 minutes because I restart the server externally with a timer.  But it did crash about 30 minutes after server load.

**Comment by DelxHQ** [comment]
I'm having a look at this

**Comment by xZeroMCPE** [comment]
It's being work on now..

**Comment by DelxHQ** [comment]
This crash is now fixed! You can get the fix from the releases page. This issue will now be closed.
