### ISSUE TITLE
You can't perform that action at this time.

### ISSUE THREAD

**Issue by CreeperFaceidk** [BukkitPE/BukkitPE#81]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [x] This issue isn't related to any plugins or plugin related crashes.
- [x] This issue isn't duplicated - Please make sure you check
- [x] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [x] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [x] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  idk why but everytime i try to create an issue or something, it says: You can't perform that action at this time. I suppose its a bug, because i don't know about any other reason.

**Comment by CreeperFaceidk** [comment]
![image](https://cloud.githubusercontent.com/assets/23064403/19706026/0ab124fa-9b10-11e6-8778-a5b281e79e64.png)

**Comment by xZeroMCPE** [comment]
-,- try now

**Comment by ghost** [comment]
You can't perform that action at this time

Sorry made some mistakes as a newb can it be fix ?

**Comment by chao-luo** [comment]
I met the same issue

**Comment by teracube** [comment]
I'm on this case
Why

You can't perform that action at this time.

**Comment by vivek50** [comment]
i am getting same problem plzz solve this..

**Comment by xZeroMCPE** [comment]
fixed

**Comment by gomoku** [comment]
@xZeroMCPE Hello, could you tell me, how did you exactly solve it (technically), because I'm experiencing the same issue on several other github trackers, can't create/edit comments etc, while on the other trackers I can, and I've already emailed github, and they've told me that it's not issue on github's side.

**Comment by vrajroham** [comment]
@gomoku Check if you installed any browser extension related to **CORS**, then disable it.

**Comment by Lancelight** [comment]
You can't perform that action at this time.
