### ISSUE TITLE
Things which needs to be added/fixed in BukkitPE

### ISSUE THREAD

**Issue by grzegorz2047** [BukkitPE/BukkitPE#85]
**LEAVE THIS IN YOUR ISSUE**<br>
Welcome to the BukkitPE issue tracker!<br>
Before you make an issue, make sure your issue matches the criteria below. We'd also encourage you to review the contributing guidelines for more information.<br>
- [ ] This issue isn't related to any plugins or plugin related crashes.
- [ ] This issue isn't duplicated - Please make sure you check
- [ ] This issue includes appropriate markdown for sections - e.g. code blocks for crash dumps.
- [ ] This issue is understandable - feel free to use your native language to write issues if you are not comfortable with English.
- [ ] This issue matches the contributing guidelines - the link is just above the title field.
  If your issue matches this criteria, hooray! Submit this issue with no worries. If your issue doesn't match this criteria, please consider editing your issue to match it. Thanks for contributing to ImagicalMine!<br>
  **START ISSUE STATEMENT BELOW**<br>
  -----------------------------

I would like to implement bukkit API in BukkitPE as much as possible.
@xZeroMCPE Could you write me what needs to be fixed in BukkitPE? I want to create list of things which can be developed by developers. If we want to push forward this project we need to know what to do.

**Comment by xZeroMCPE** [comment]
@grzegorz2047 Will be making a list of it on a new issue im making!

**Comment by xZeroMCPE** [comment]
Check my issue and feel free to add any thing on it!
