### ISSUE TITLE
Stable Build Crashing

### ISSUE THREAD

**Issue by MunkySkunk** [BukkitPE/BukkitPE#9]
This server is running BukkitPE 1.0dev 「Stable_V1」 implementing API version 1.13.1 for Minecraft: PE v0.13.1 alpha (protocol version 38)

It keeps crashing with the below crash file. No Plugins are loaded.

BukkitPE Crash Dump Thu Feb 4 12:55:07 UTC 2016

Error: Class pocketmine\scheduler\AsyncTask not found
File: /src/spl/BaseClassLoader
Line: 128
Type: notice

THIS CRASH WAS CAUSED BY A PLUGIN

Code:
[119] 
[120]           if(method_exists($name, "onClassLoaded") and (new ReflectionClass($name))->getMethod("onClassLoaded")->isStatic()){
[121]               $name::onClassLoaded();
[122]           }
[123]  
[124]           $this->classes[] = $name;
[125] 
[126]             return true;
[127]         }elseif($this->getParent() === null){
[128]           throw new ClassNotFoundException("Class $name not found");
[129]         }
[130] 
[131]         return false;
[132]     }
[133] 
[134]     /**
[135]      \* Returns the path for the class, if any
[136]      *
[137]      \* @param string $name
[138]      *

Backtrace:
#0 /src/BukkitPE/scheduler/GarbageCollectionTask(4): spl_autoload_call(string pocketmine\scheduler\AsyncTask)
#1 /src/spl/BaseClassLoader(112): include(string phar://C:/PocketMine-MP/BukkitPE.phar/src/BukkitPE/scheduler/GarbageCollectionTask.php)
#2 (): BaseClassLoader->loadClass(string BukkitPE\scheduler\GarbageCollectionTask)
#3 /src/BukkitPE/MemoryManager(186): spl_autoload_call(string BukkitPE\scheduler\GarbageCollectionTask)
#4 /src/BukkitPE/MemoryManager(174): BukkitPE\MemoryManager->triggerGarbageCollector(boolean)
#5 /src/BukkitPE/Server(2549): BukkitPE\MemoryManager->check(boolean)
#6 /src/BukkitPE/Server(2237): BukkitPE\Server->tick(boolean)
#7 /src/BukkitPE/Server(2115): BukkitPE\Server->tickProcessor(boolean)
#8 /src/BukkitPE/Server(1708): BukkitPE\Server->start(boolean)
#9 /src/BukkitPE/BukkitPE(449): BukkitPE\Server->__construct(BukkitPE\CompatibleClassLoader object, BukkitPE\utils\MainLogger object, string phar://C:\PocketMine-MP\BukkitPE.phar/, string C:\PocketMine-MP\, string C:\PocketMine-MP\plugins)
#10 (1): require_once(string phar://C:/PocketMine-MP/BukkitPE.phar/src/BukkitPE/BukkitPE.php)

BukkitPE-MP version: 1.0dev #0 [Protocol 38; API 1.13.1]
Git commit: 0000000000000000000000000000000000000000
uname -a: Windows NT USER-HP 6.1 build 7601 (Windows 7 Business Edition Service Pack 1) i586
PHP Version: 5.6.6
Zend version: 2.6.0
OS : WINNT, win

Loaded plugins:

**Comment by meetloaf13** [comment]
Pretty sure my crash is the same.

**Comment by DelxHQ** [comment]
I'll have a look at this.

**Comment by MunkySkunk** [comment]
Has a patch been release for this as I have had to revert back to pocketmine for the time being.

**Comment by DelxHQ** [comment]
I'm releasing this now.

**Comment by DelxHQ** [comment]
@AndreTheGamer I fixed this..

**Comment by DelxHQ** [comment]
This crash is now fixed! You can get the fix from the releases page. This issue will now be closed.

**Comment by MunkySkunk** [comment]
Would you be able to assist in advising what i need to do to get the latest patch.

**Comment by xZeroMCPE** [comment]
Hi, please visit our site: www.BukkitPE.net then there you can see all infos you need to know, If you are looking for help please click forum on our main site. Then registered on the forum and ask for help and we will assit you faster. Thanks :)
